from datetime import datetime
from djongo.models import Model, ObjectIdField, CharField, BooleanField, FloatField, DateField


class appraisal_data(Model):
    _id = ObjectIdField()
    Designation =CharField(max_length=100)
    Employee_id = CharField(max_length=100)
    Department = CharField(max_length=100)
    date = DateField(auto_now_add=True)
    Academic_Score_cumulative = FloatField(max_length=100)
    Academic_Score_achived = FloatField(max_length=100)
    Acadaemic_proof = CharField(max_length=100000)
    types = CharField(max_length=100)
    course_cumulative = FloatField(max_length=100)
    course_achived = FloatField(max_length=100)
    course_proof = CharField(max_length=100000)
    c_types = CharField(max_length=100)
    fdp_cumulative = FloatField(max_length=100)
    fdp_achived = FloatField(max_length=100)
    fdp_proof = CharField(max_length=100000)
    counselling_cumulative = FloatField(max_length=100)
    counselling_achived = FloatField(max_length=100)
    counselling_proof = CharField(max_length=100000)
    Student_Feedback_cumulative = FloatField(max_length=100)
    Student_Feedback_achived = FloatField(max_length=100) 
    Student_feedback_proof = CharField(max_length=100000)
    precption_cumulative = FloatField(max_length=100)
    precption_achived = FloatField(max_length=100) 
    precption_proof = CharField(max_length=100000) 
    Institutional_Coordinators_cumulative = CharField(max_length=100)
    Institutional_Coordinators_achived = CharField(max_length=100)
    Institutional_coordinators_proof = CharField(max_length=100000)
    research_paper_cumulative = FloatField(max_length=100)
    research_paper_achived = FloatField(max_length=100)
    research_paper_proof = CharField(max_length=100000)
    paper_presentaion_cumulative = FloatField(max_length=100)
    paper_presentaion_achived = FloatField(max_length=100)
    paper_presentaion_proof = CharField(max_length=100000)
    Research_project_sanctioned_cumulative = FloatField(max_length=100)
    Research_project_sanctioned_achived = FloatField(max_length=100)
    Research_project_sanctioned_proof = CharField(max_length=100000)
    Research_proposal_cumulative = FloatField(max_length=100)
    Research_proposal_achived = FloatField(max_length=100)
    research_proposal_proof = CharField(max_length=100000)
    Consultancy_cumulative =  FloatField(max_length=100)
    Consultancy_achived = FloatField(max_length=100)
    Consultancy_proof = CharField(max_length=100000)
    pedagogy_cumulative = FloatField(max_length=100)
    pedagogy_achived = FloatField(max_length=100)
    pedagogy_proof = CharField(max_length=100000)
    inovative_cumulative = FloatField(max_length=100)
    inovative_achived = FloatField(max_length=100)
    inovative_proof = CharField(max_length=100000)
    E_Content_development_cumulative = FloatField(max_length=100)
    E_Content_development_achived = FloatField(max_length=100)
    E_content_proof = CharField(max_length=100000)


class appraisal_data_monthwise(Model):
    _id = ObjectIdField()
    Designation =CharField(max_length=100)
    Employee_id = CharField(max_length=100)
    Department = CharField(max_length=100)
    date = DateField(auto_now_add=True)
    Academic_Score_cumulative = FloatField(max_length=100)
    Academic_Score_achived = FloatField(max_length=100)
    Acadaemic_proof = CharField(max_length=100000)
    types = CharField(max_length=100)
    course_cumulative = FloatField(max_length=100)
    course_achived = FloatField(max_length=100)
    course_proof = CharField(max_length=100000)
    c_types = CharField(max_length=100)
    fdp_cumulative = FloatField(max_length=100)
    fdp_achived = FloatField(max_length=100)
    fdp_proof = CharField(max_length=100000)
    counselling_cumulative = FloatField(max_length=100)
    counselling_achived = FloatField(max_length=100)
    counselling_proof = CharField(max_length=100000)
    Student_Feedback_cumulative = FloatField(max_length=100)
    Student_Feedback_achived = FloatField(max_length=100) 
    Student_feedback_proof = CharField(max_length=100000)
    precption_cumulative = FloatField(max_length=100)
    precption_achived = FloatField(max_length=100) 
    precption_proof = CharField(max_length=100000) 
    Institutional_Coordinators_cumulative = CharField(max_length=100)
    Institutional_Coordinators_achived = CharField(max_length=100)
    Institutional_coordinators_proof = CharField(max_length=100000)
    research_paper_cumulative = FloatField(max_length=100)
    research_paper_achived = FloatField(max_length=100)
    research_paper_proof = CharField(max_length=100000)
    paper_presentaion_cumulative = FloatField(max_length=100)
    paper_presentaion_achived = FloatField(max_length=100)
    paper_presentaion_proof = CharField(max_length=100000)
    Research_project_sanctioned_cumulative = FloatField(max_length=100)
    Research_project_sanctioned_achived = FloatField(max_length=100)
    Research_project_sanctioned_proof = CharField(max_length=100000)
    Research_proposal_cumulative = FloatField(max_length=100)
    Research_proposal_achived = FloatField(max_length=100)
    research_proposal_proof = CharField(max_length=100000)
    Consultancy_cumulative =  FloatField(max_length=100)
    Consultancy_achived = FloatField(max_length=100)
    Consultancy_proof = CharField(max_length=100000)
    pedagogy_cumulative = FloatField(max_length=100)
    pedagogy_achived = FloatField(max_length=100)
    pedagogy_proof = CharField(max_length=100000)
    inovative_cumulative = FloatField(max_length=100)
    inovative_achived = FloatField(max_length=100)
    inovative_proof = CharField(max_length=100000)
    E_Content_development_cumulative = FloatField(max_length=100)
    E_Content_development_achived = FloatField(max_length=100)
    E_content_proof = CharField(max_length=100000)    
    query = BooleanField(default=False)
    hod_approved = BooleanField(default=False)
    hod_approved_date = DateField(default=datetime(2023, 1, 1))
    dean_approved = BooleanField(default=False)
    dean_approved_date = DateField(default=datetime(2023, 1, 1))
    chairman_approved = BooleanField(default=False)
    chairman_approved_date = DateField(default=datetime(2023, 1, 1))
    commitment_undertaking1 = CharField(max_length=100)
    commitment_undertaking2 = CharField(max_length=100)
    additional_information = CharField(max_length=100)


